---
- name: php-fpm installed
  yum: name=php55u-fpm enablerepo=ius

- name: php-fpm.conf changed
  template: src=php-fpm.conf.j2 dest=/etc/php-fpm.conf
- name: php-fpm.conf changed
  template: src=php-fpm-www.conf.j2 dest=/etc/php-fpm.d/www.conf

- name: php-fpm started and enabled
  service: name=php-fpm state=restarted enabled=yes
