---
- name: git checkout rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
  sudo: yes
- name: change owner and group
  file: dest=/home/vagrant/.rbenv state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
  sudo: yes

- name: edit PATH rbenv on .bash_profile
  lineinfile: dest={{ bash_profile }} line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: edit rbenv init on .bash_profile
  lineinfile: dest={{ bash_profile }} line="eval \"$(rbenv init -)\""

- name: git checkout ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/vagrant/.rbenv/plugins/ruby-build
  sudo: yes

- name: git checkout rbenv-gem-rehash
  git: repo=https://github.com/sstephenson/rbenv-gem-rehash.git dest=/home/vagrant/.rbenv/plugins/rbenv-gem-rehash
  sudo: yes

- name: change owner and group
  file: dest=/home/vagrant/.rbenv/plugins state=directory mode=0755 recurse=yes owner=vagrant group=vagrant
  sudo: yes

- name: build environment
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - cmake
    - openssl-devel
    - libyaml-devel
    - readline-devel
    - zlib-devel

- name: ruby 2.1.4 installed by rbenv
  command: sudo -u vagrant -i -- rbenv install 2.1.4
  ignore_errors: yes

- command: sudo -u vagrant -i -- rbenv rehash
- command: sudo -u vagrant -i -- rbenv global 2.1.4

